USE TRANDAIANHMINH
--4
SELECT COUNT(PHAI) AS 'So luong sinh vien nam'
FROM SV_SE162088
WHERE PHAI = 'Nam'

SELECT COUNT(PHAI) AS 'So luong sinh vien nu'
FROM SV_SE162088
WHERE PHAI = 'Nu'

--5
CREATE PROC FnSinhvien ( @HOSV varchar(25), @TENSV VARCHAR(20), @NGAYSINH DATE)
 AS
    BEGIN
        IF EXISTS (SELECT * FROM SV_SE162088 WHERE @HOSV = HOSV AND @TENSV= TENSV AND @NGAYSINH = NGAYSINH)
            SELECT MASV FROM SV_SE162088 WHERE @HOSV = HOSV AND @TENSV= TENSV AND @NGAYSINH = NGAYSINH
    END
GO
--CREATE TABLE SV_SE162088(
--MASV VARCHAR(8) PRIMARY KEY,
--HOSV      VARCHAR(25)  NOT NULL,
--TENSV     VARCHAR(20)  NOT NULL,
--PHAI VARCHAR(3) NOT NULL,
--NGAYSINH DATE NOT NULL,
--NOISINH VARCHAR(30)
--)